site:
  title: Pipelite Framework
  url: https://docs.pipelite.io
  start_page: pipelite::index.adoc
  keys:
    repo_url: https://github.com/pipelite-projects/pipelite-framework

content:
  sources:
  - url: ..
    branches: HEAD
    start_path: framework-docs
  - url: https://github.com/pipelite-projects/pipelite-framework.git
    branches: []
    tags: v*
    start_path: framework-docs

urls:
  latest_version_segment: latest

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    attribute-missing: warn
    chomp: all
    page-pagination: ''
    source-highlighter: highlight.js
    highlightjs-languages: java,xml,yaml
    project-group-id: io.pipelite

output:
  dir: ./build/site
