name: PR Management

on:
  pull_request:
    types: [ opened ]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author to the PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            })